name: firebase_trial
description: "A new Flutter project."
publish_to: "none"
version: 0.1.0

environment:
  sdk: ^3.6.0

dependencies:
  flutter:
    sdk: flutter
  firebase: ^9.0.3
  cloud_firestore: ^5.6.0
  firebase_core: ^3.9.0
  shimmer: ^3.0.0
  firebase_auth: ^5.3.4
  flutter_animate: ^4.5.2
  carousel_slider: ^5.0.0

dev_dependencies:
  flutter_test:
    sdk: flutter
  flutter_lints: ^5.0.0

flutter:
  uses-material-design: true
  assets:
    - assets/
